/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.furb.linguagensformais.aplicacao.view;

import br.furb.linguagensformais.aplicacao.Automato;
import br.furb.linguagensformais.aplicacao.Palavra;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Flávio e Carol
 */
public class Aplicacao extends javax.swing.JFrame {
    private List<Palavra> lstPalavra;
    private DefaultTableModel tableModel;
    private String[] limparTableModel;
    private Automato automato;
    
    /**
     * Creates new form Aplicacao
     */
    public Aplicacao() {
        initComponents();
        this.formatarTela();
        this.inicializarCampos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JB_Analisar = new javax.swing.JButton();
        JB_Limpar = new javax.swing.JButton();
        JB_Equipe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_CampoA = new javax.swing.JTextArea();
        JSP_CampoB = new javax.swing.JScrollPane();
        JT_CampoB = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(864, 410));

        JB_Analisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/furb/linguagensformais/aplicacao/imagens/forward.png"))); // NOI18N
        JB_Analisar.setText("Analisar");
        JB_Analisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AnalisarActionPerformed(evt);
            }
        });

        JB_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/furb/linguagensformais/aplicacao/imagens/editcut.png"))); // NOI18N
        JB_Limpar.setText("Limpar");
        JB_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LimparActionPerformed(evt);
            }
        });

        JB_Equipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/furb/linguagensformais/aplicacao/imagens/system-users.png"))); // NOI18N
        JB_Equipe.setText("Equipe");
        JB_Equipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EquipeActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(864, 187));

        JTA_CampoA.setColumns(20);
        JTA_CampoA.setRows(5);
        jScrollPane2.setViewportView(JTA_CampoA);

        JSP_CampoB.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        JSP_CampoB.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        JSP_CampoB.setPreferredSize(new java.awt.Dimension(864, 173));

        JT_CampoB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_CampoB.setViewportView(JT_CampoB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JB_Analisar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Equipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JSP_CampoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JB_Limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JB_Analisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Equipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JSP_CampoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AnalisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AnalisarActionPerformed
        this.analisar();
    }//GEN-LAST:event_JB_AnalisarActionPerformed

    private void JB_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LimparActionPerformed
        this.limparCampoA();
        this.limparCampoB();
    }//GEN-LAST:event_JB_LimparActionPerformed

    private void JB_EquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EquipeActionPerformed
        JOptionPane.showMessageDialog(null, "Alunos: Flávio Omar Losada e\n" 
                                   + "               Gabriel da Silva Bernardi");
    }//GEN-LAST:event_JB_EquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Errado".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Aplicacao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Analisar;
    private javax.swing.JButton JB_Equipe;
    private javax.swing.JButton JB_Limpar;
    private javax.swing.JScrollPane JSP_CampoB;
    private javax.swing.JTextArea JTA_CampoA;
    private javax.swing.JTable JT_CampoB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void formatarTela(){
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void inicializarCampos(){
        this.JTA_CampoA.setBorder(new NumberedBorder());
        this.definirtamanhoColunaJTable();
        this.tableModel = (DefaultTableModel) this.JT_CampoB.getModel();
        this.limparTableModel = new String[4];
        this.limparCampoA();
        this.limparCampoB();
    }
    
    private void definirtamanhoColunaJTable(){
        this.JT_CampoB.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);  
        this.JT_CampoB.getColumnModel().getColumn(0).setPreferredWidth(50);  
        this.JT_CampoB.getColumnModel().getColumn(1).setPreferredWidth(150);  
        this.JT_CampoB.getColumnModel().getColumn(2).setPreferredWidth(250);  
        this.JT_CampoB.getColumnModel().getColumn(3).setPreferredWidth(406);  
    }
    
    private void limparCampoA(){
        this.JTA_CampoA.setText("");
    }
    
    private void limparCampoB(){
        this.tableModel.getDataVector().setSize(0);
        for (int linha = 0; linha < 8; linha++) {
            tableModel.addRow(this.limparTableModel);
        }
    }
    
    private void analisar() {
        this.lstPalavra = new ArrayList<>();
        this.limparCampoB();
        this.procurarPalavras();
        this.popularJTable();
    }
    
    public void procurarPalavras(){
        String texto = this.JTA_CampoA.getText();
        
        String[] linha = texto.split("\\n");
        for (int numeroLinha = 0; numeroLinha < linha.length; numeroLinha++) {
            String separarPalavras = linha[numeroLinha].replace(" ", "\n").replace("\t", "\n");
            String[] sequencias = separarPalavras.split("\\n");
            for (String sequencia : sequencias) {
                if (this.possuiSimboloEspecial(sequencia)) {
                    String[] sequenciasSimbolosEspeciais = this.separarSequenciaSimboloEspecial(sequencia);
                    for (String sequenciaSimboloEspeciai : sequenciasSimbolosEspeciais) {
                        if (!sequenciaSimboloEspeciai.isEmpty()){
                            this.lstPalavra.add(this.criarPalavra(sequenciaSimboloEspeciai, numeroLinha));
                        }
                    }
                } else if (!sequencia.equals("")) {
                    this.lstPalavra.add(this.criarPalavra(sequencia, numeroLinha));
                }
            }
        }
    }
    
    private Palavra criarPalavra(String sequencia, int numeroLinha){
        Palavra palavra = new Palavra();
        this.automato = new Automato();
        this.automato.q0(sequencia);
        
        palavra.setSequencia(sequencia);
        palavra.setLinha(numeroLinha + 1);
        palavra.setResultado(this.automato.getResultado());
        palavra.setReconhecimento(this.automato.getReconhecimento().toString());
        return palavra;
    }

    private boolean possuiSimboloEspecial(String palavra) {
        return palavra.contains(";") || palavra.contains(".") 
                || palavra.contains(",");
    }
    
    private String[] separarSequenciaSimboloEspecial(String sequencia){
        String[] caracteres = sequencia.split("");
        StringBuilder palavras = new StringBuilder();
        for (String caracter : caracteres) {
            if (caracter.equals(";") || caracter.equals(".") || caracter.equals(",")) {
                palavras.append("\n").append(caracter).append("\n");
            } else {
                palavras.append(caracter);
            }
        }
        return palavras.toString().split("\n");
    }
    
    private void popularJTable() {
        this.tableModel.getDataVector().setSize(0);
        
        int controleLinhasEmBranco = 0;
        for(Palavra p : this.lstPalavra){
            Object[] row = new Object[4];
            row[0] = p.getLinha();
            row[1] = p.getResultado();
            row[2] = p.getSequencia();
            row[3] = p.getReconhecimento();
            tableModel.addRow(row);
            controleLinhasEmBranco++;
        }
        for (; controleLinhasEmBranco < 8; controleLinhasEmBranco++) {
            tableModel.addRow(this.limparTableModel);
        }
    }
}