/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.furb.linguagensformais.aplicacao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Flávio e Carol
 */
public class Aplicacao extends javax.swing.JFrame {
    private List<Palavra> lstPalavra = null;
    private DefaultTableModel model;
    private String[] limparModel;
    private Automato automato;
    
    /**
     * Creates new form Aplicacao
     */
    public Aplicacao() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.JTA_Editor_Palavras.setBorder(new NumberedBorder());
        this.model = (DefaultTableModel) this.JTable_Valores.getModel();
        this.limparModel = new String[4];
        this.lstPalavra = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_Editor_Palavras = new javax.swing.JTextArea();
        JB_Analisar = new javax.swing.JButton();
        JB_Limpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_Valores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JTA_Editor_Palavras.setColumns(20);
        JTA_Editor_Palavras.setRows(5);
        jScrollPane1.setViewportView(JTA_Editor_Palavras);

        JB_Analisar.setText("Analisar");
        JB_Analisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AnalisarActionPerformed(evt);
            }
        });

        JB_Limpar.setText("Limpar");
        JB_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LimparActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JTable_Valores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTable_Valores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Analisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_Limpar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Analisar)
                    .addComponent(JB_Limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AnalisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AnalisarActionPerformed
        this.lstPalavra = new ArrayList<>();
        this.analisar();
    }//GEN-LAST:event_JB_AnalisarActionPerformed

    private void JB_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LimparActionPerformed
        this.limparCampos();
//        model.getDataVector().setSize(0);
//        for (int i = 0; i < 9; i++)
//            model.addRow(limparModel);
    }//GEN-LAST:event_JB_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Aplicacao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Analisar;
    private javax.swing.JButton JB_Limpar;
    private javax.swing.JTextArea JTA_Editor_Palavras;
    private javax.swing.JTable JTable_Valores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        this.JTA_Editor_Palavras.setText("");
        this.automato = new Automato();
    }
    
    private void analisar() {
        this.getPalavras(this.JTA_Editor_Palavras.getText());
        this.popularJTable();
    }
    
    private void popularJTable() {
        model.getDataVector().setSize(0);
        
        int cont = 0;
        for(Palavra p : this.lstPalavra){
            Object[] row = new Object[4];
            row[0] = p.getLinha();
            row[1] = p.getResultado();
            row[2] = p.getSequencia();
            row[3] = p.getReconhecimento();
            model.addRow(row);
            cont++;
        }
        
        for (; cont < 9; cont++) {
            model.addRow(this.limparModel);
        }
    }
    
    public void getPalavras(String text){
        String[] linha = text.split("\\n");
        for (int numeroLinha = 0; numeroLinha < linha.length; numeroLinha++) {
            String palavraFormatada = linha[numeroLinha].replace(" ", "\n").replace("\t", "\n");
            String[] sequencias = palavraFormatada.split("\\n");
            for (String sequencia : sequencias) {
                if (this.simboloEspecial(sequencia)) {
                    String[] simbolosPalavras = this.obterSequenciaEspecial(sequencia);
                    for (String simbolosPalavra : simbolosPalavras) {
                        this.lstPalavra.add(this.criarPalavra(simbolosPalavra, numeroLinha));
                    }
                } else if (!sequencia.equals("")) {
                    this.lstPalavra.add(this.criarPalavra(sequencia, numeroLinha));
                }
            }
        }
    }
    
    private Palavra criarPalavra(String sequencia, int numeroLinha){
        Palavra palavra = new Palavra();
        if (!sequencia.isEmpty()){
            this.automato = new Automato();
            this.automato.q0(sequencia, 0);
        }
        palavra.setSequencia(sequencia);
        palavra.setLinha(numeroLinha + 1);
        palavra.setResultado(this.automato.getResultado());
        palavra.setReconhecimento(this.automato.getReconhecimento().toString());
        return palavra;
    }

    /**
     * Feito para Teste, não vai ser feito assim
     * @param seq
     * @return 
     */
    public EnumResultado sequenciaValida(String seq){
//        String rotulo = EnumRotuloReconhecimento.Q0.getRotulo();
//        for (int i = 0; i < seq.length(); i++) {
//            char caractere = seq.charAt(i);
//            if (caractere == 'a' || caractere == 'b' || caractere == 'c'){
//                if (rotulo.equals(EnumRotuloReconhecimento.Q1_Q5.getRotulo())){
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q1_Q6.getRotulo();
//                    } else if (caractere == 'b'){
//                        rotulo = EnumRotuloReconhecimento.Q2.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q7.getRotulo())){
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'b' || caractere == 'c'){
//                        rotulo = EnumRotuloReconhecimento.Q8.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q1_Q6.getRotulo())){
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q1_Q5.getRotulo();
//                    } else if (caractere == 'b'){
//                        rotulo = EnumRotuloReconhecimento.Q2_Q7.getRotulo();
//                    } else {
//                        rotulo = EnumRotuloReconhecimento.Q7.getRotulo();
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q2.getRotulo())) {
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q3.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q8.getRotulo())) {
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'b' || caractere == 'c'){
//                        rotulo = EnumRotuloReconhecimento.Q7.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q2_Q7.getRotulo())) {
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q3.getRotulo();
//                    } else if (caractere == 'b' || caractere == 'c'){
//                        rotulo = EnumRotuloReconhecimento.Q8.getRotulo();
//                    } 
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q3.getRotulo())) {
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q4.getRotulo();
//                    } else if (caractere == 'b'){
//                        rotulo = EnumRotuloReconhecimento.Q2.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    }
//                } else if (rotulo.equals(EnumRotuloReconhecimento.Q4.getRotulo())) {
//                    caminho.append(", ").append(rotulo);
//                    if (caractere == 'a'){
//                        rotulo = EnumRotuloReconhecimento.Q3.getRotulo();
//                    } else {
//                        caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                        return EnumResultado.PALAVRA_INVALIDA;
//                    } 
//                }
//            } else {
//                caminho.append(", ").append(EnumRotuloReconhecimento.Q_ERRO.getRotulo());
//                for (int j = 0; j < seq.length(); j++) {
//                    char palavraEspecial = seq.charAt(j);
//                    if (this.caracteresEspecificos.contains(palavraEspecial)){
//                        return EnumResultado.PALAVRA_VALIDA;
//                    }
//                }
//                return EnumResultado.SIMBOLO_ESPECIAL;
//            }
//        }
//        this.caminho.append(", ").append(rotulo);
        return EnumResultado.PALAVRA_INVALIDA;
    }

    private boolean simboloEspecial(String palavra) {
        return palavra.contains(";") || palavra.contains(".") 
                || palavra.contains(",");
    }
    
    private String[] obterSequenciaEspecial(String sequencia){
        String[] separarCaracteres = sequencia.split("");
        StringBuilder palavras = new StringBuilder();
        for (String separarCaractere : separarCaracteres) {
            if (!separarCaractere.equals(";") && !separarCaractere.equals(".") && !separarCaractere.equals(",")) {
                palavras.append(separarCaractere);
            } else {
                palavras.append("\n").append(separarCaractere);
            }
        }
        return palavras.toString().split("\n");
    }
}